### ISSUE TITLE
GTOT RGBT234等数据集的属性

### ISSUE THREAD

**Issue by QRR520** [xingchenzhang/RGB-T-fusion-tracking-papers-and-results#1]
您好，打扰了，有一个问题想向您请教一下，关于GTOT RGBT210 RGBT234的属性标注在哪里可以查看？我下载了数据集，但是发现数据集中只有每个视频的GT标注，没有找到关于属性的标注

**Comment by xingchenzhang** [comment]
不好意思，才看到。

我记得是有关于属性的excel表格的。已在repo中上传。RGBT210是RGBT234的子集，所以包含在内了。
