### ISSUE TITLE
can't link RGBT234 Google Drive

### ISSUE THREAD

**Issue by xiaofeinot** [xingchenzhang/RGB-T-fusion-tracking-papers-and-results#2]
![image](https://user-images.githubusercontent.com/43447136/97582472-bf969000-1a30-11eb-97c4-0455cc03057f.png)
Thanks for youtr work, it's useful for us freshmen in the RGBT tracking .But the Google Drive link of RGBT234 is not available as the picture shows, can you help fix it?

**Comment by xingchenzhang** [comment]
Hi @xiaofeinot,

Sorry for this. I have fixed it and you can try again.

Bests,
Xingchen
