### ISSUE TITLE
No code!

### ISSUE THREAD

**Issue by najingligong1111** [xingchenzhang/RGB-T-fusion-tracking-papers-and-results#3]

**Comment by xingchenzhang** [comment]
Sorry, most RGB-T tracking methods are not open-source. But when I am free I will try to find and add some code links.

**Comment by trathpai** [comment]
What is the license for Dataset?

**Comment by xingchenzhang** [comment]
> What is the license for Dataset?

Hi,

For the license, please check with Prof. Cheng Li from Anhui University, China. He is the author of these datasets.

Thanks!
